### ISSUE TITLE
Upgrade DW and Jackson

### ISSUE THREAD

**Issue by danielfc** [yunspace/dropwizard-xml#7]
Hey guys,

Would be possible to upgrade DW to 0.9.2 and Jackson to 2.7.5?

Thanks!

**Comment by danielfc** [comment]
would be nice to see these upgrades

```
[ERROR] Failed to execute goal on project be-acctrest: Could not resolve dependencies for project com.tradier:be-acctrest:jar:0.0.1: Failed to collect dependencies at com.yunspace.dropwizard:dropwizard-xml:jar:0.9.0-30 -> io.dropwizard:dropwizard-core:jar:0.9.0-SNAPSHOT: Failed to read artifact descriptor for io.dropwizard:dropwizard-core:jar:0.9.0-SNAPSHOT: Could not transfer artifact io.dropwizard:dropwizard-core:pom:0.9.0-SNAPSHOT from/to codehaus-snapshots
```

**Comment by yunspace** [comment]
Hi @danielfc sorry for the delay, will take a look. Welcome any PRs also. 

Ideally I wanted to make this library version independent post DW 0.9 / 1.0.0. I.e. by using the maven `provided` keyword instead of hard coding DW versions.

**Comment by danielfc** [comment]
that's a good idea, looking forward to seeing it live :smile:

**Comment by yunspace** [comment]
I've updated the library so that it the DW and Jackson dependencies need to be provided by the user. (similar to the "provided" scope in maven). See README for updated instructions. 

If you want to use DW 0.9.2, you must use Jackson 2.6.3 to avoid conflicts with  DW's maven enforcer plugin. It will only work with DW XML 39 and you still need to add the `jdk7` module. The latest version so far.

If you want to upgrade to Jackson 2.7.5 and skip the `jdk7` module, then upgrade to DW 1.0.0-rc4 and use DW XML 40+ which will be released soon.
